---
abstract: 'Check for uncleaned imports'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CleanNamespaces
requires:
  Class::MOP: 0
  File::Find::Rule: 0
  File::Find::Rule::Perl: 0
  File::Spec::Functions: 0
  Sub::Exporter: 0
  Sub::Name: 0
  Test::Builder: 0
  Test::Tester: 0
  namespace::autoclean: 0
version: 0.02
